services:
  bob2build-website:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bob2build
    ports:
      - "6000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SITE_URL=https://bob2build.tanmaydeepsharma.com
    restart: unless-stopped
